## Installation stuff

# install: make .

language: c

notifications:
        slack: design3e1:TwMxEB4gtYnqe3WITrBwO5Ae
        email: false
        

install:
- sudo apt-get install libopencv-dev

script:
 - cd samples/opencv
 - sh ./build.sh
 - cd ../..
 - cd test
 - sh ./run_test.sh

compiler: clang
