## Installation stuff

# install: make .

sudo: required

language: c
    
services:
  - docker

before_install:
  - cd dockertest
  - docker pull jbharvey/typhoon
  - docker build jbharvey/typhoon .


notifications:
        slack: design3e1:TwMxEB4gtYnqe3WITrBwO5Ae
        email: false
        

install:
    #  - sudo apt-get install libopencv-dev
    #  - sudo ln /dev/null /dev/raw1394

script:
  - ls -lAh
  - pwd
  - cd dockertest
  - ./runtest.sh
    #  - cd samples/opencv
    #  - sh ./build.sh
    #  - cd ../..
    #  - cd test
    #  - ./run_test.sh

#compiler: clang
