sudo: required

language: c
    
services:
    - docker

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libopencv-dev libgtk-3-dev
    - docker pull jbharvey/typhoon
    - sudo ln /dev/null /dev/raw1394


notifications:
    slack: design3e1:TwMxEB4gtYnqe3WITrBwO5Ae
    email: false
        

install:

script:
    - ./run-tests.sh
    
#compiler: clang
