dist: trusty
sudo: required

language: c
    
services:
    - docker

before_install:
    - sudo add-apt-repository -y ppa:amarburg/opencv3
    - sudo apt-get -qq update
    - docker pull jbharvey/typhoon


notifications:
    slack: design3e1:TwMxEB4gtYnqe3WITrBwO5Ae
    email: false        

install:
    - sudo apt-get install libopencv-dev libgtk-3-dev libev-dev
    - sudo ln /dev/null /dev/raw1394

script:
    - ./run-tests.sh

#compiler: clang
