#ifndef COM_H_
#define COM_H_

#include "stm32f4xx.h"

enum COMMAND {
	COMMAND_MOVE = 0,
	COMMAND_START_IDEN_WHEELS = 65,
	COMMAND_IDEN_WHEELS = 66,
	COMMAND_START_TEST_PID_SPEED = 67,
	COMMAND_SEND_PID_SPEED = 68,
	COMMAND_ROTATE = 1,
	COMMAND_TURN_RED_LED_ON = 2,
	COMMAND_TURN_GREEN_LED_ON = 3,
	COMMAND_PENCIL_UP = 4,
	COMMAND_PENCIL_DOWN = 5,
	COMMAND_DECODE_MANCHESTER = 6,
	COMMAND_STOP_DECODE_MANCHESTER = 7,
	COMMAND_DECODED_MANCHESTER = 106
};

extern uint8_t bFlagSendData;

#include "stm32f4xx.h"
#include "tm_stm32f4_usb_vcp.h"

uint8_t readUSB();

#endif
