#ifndef UTILS_H_
#define UTILS_H_

#include "defines.h"

enum State {
	IDLE,
	GENERATE_FIRST_PWM,
	BETWEEN_PWM,
	ACQUIRE,
	SEND_DATA,
	WAIT_FOR_SECOND_PWM
};

enum MainState {
	MAIN_IDLE,
	MAIN_MANCH,
	MAIN_ACQUIS,
	MAIN_ACQUIS_ALL,
	MAIN_TEST_SPEED_PID,
	MAIN_TEST_POS_PID,
	MAIN_TEST_DEAD_ZONE,
	MAIN_MOVE,
	MAIN_PID,
	MAIN_PREHENSEUR,
	MAIN_MOVE_UP_PREHENSOR,
	MAIN_MOVE_DOWN_PREHENSOR,
	MAIN_STOP_SENDING_MANCHESTER_SIGNAL,
	MAIN_TURN_ON_RED_LED,
	MAIN_TURN_GREEN_LED
};

enum SpeedDirection {
	SPEED_DIRECTION_FORWARD, SPEED_DIRECTION_BACKWARD, SPEED_DIRECTION_NONE
};

enum AmountOfCharacters {
	ONE_CHARACTER, MANY_CHARACTERS
};

enum COMMUNICATION_STATUS {
	READ_USB_SUCCESS, READ_USB_FAIL
};

void cleanNumberString(char *numberString, int size);

void setState(int* state, int newState);

float sqroot(float square);

#endif
